service: voice-insight-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 3008
  timeout: 900
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    ENVIRONMENT: production
    LOG_LEVEL: INFO
    CLOUDWATCH_NAMESPACE: VoiceInsight
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  api:
    handler: lambda_handler.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true